/*
 * LEXSTAR — Archive data
 * 12 articles across 3 weeks. Phase 7 replaces with live database queries.
 */

export const ARCHIVE_ARTICLES = [
  // ── Week of 10–16 Feb ──────────────────────────────────────────────────────
  {
    id: "a1",
    category: "legal",
    headline: "Supreme Court Rules on SEC Enforcement Authority in Landmark Case",
    brief: "A 6-3 ruling limits the SEC's ability to seek disgorgement in insider trading cases heard by its own administrative judges, shifting significant disputes to federal courts.",
    tags: ["SEC", "United States", "Regulation", "Litigation"],
    sources: ["SCOTUSblog", "WSJ", "Law360"],
    time: "10 Feb",
    date: "2025-02-10",
    market: null,
    verified: true,
  },
  {
    id: "a2",
    category: "finance",
    headline: "Goldman Sachs Posts Record Q4 Trading Revenue of $8.2 Billion",
    brief: "Fixed-income and equity trading desks outperformed consensus estimates by 18%, driven by elevated bond market volatility and a surge in derivatives hedging activity.",
    tags: ["Goldman Sachs", "Banking", "United States", "Markets"],
    sources: ["Bloomberg", "FT", "Reuters"],
    time: "11 Feb",
    date: "2025-02-11",
    market: "NYSE",
    verified: true,
  },
  {
    id: "a3",
    category: "markets",
    headline: "ECB Cuts Rates by 25bps to 3.25% Amid Slowing Eurozone Growth",
    brief: "The European Central Bank's third consecutive cut follows GDP growth of just 0.1% in Q4, with President Lagarde signalling further reductions if inflation remains subdued.",
    tags: ["European Union", "Monetary Policy", "Banking", "Euronext"],
    sources: ["Reuters", "FT", "ECB Press Release"],
    time: "12 Feb",
    date: "2025-02-12",
    market: "Euronext",
    verified: true,
  },
  {
    id: "a4",
    category: "legal",
    headline: "FCA Fines Barclays £40m for Client Money Segregation Failures",
    brief: "The Financial Conduct Authority found that Barclays failed to properly segregate approximately £2.4bn in client assets over a 14-month period, breaching CASS rules.",
    tags: ["Compliance", "United Kingdom", "Banking", "Regulation"],
    sources: ["FCA", "FT", "Reuters"],
    time: "14 Feb",
    date: "2025-02-14",
    market: "LSE",
    verified: true,
  },

  // ── Week of 3–9 Feb ────────────────────────────────────────────────────────
  {
    id: "a5",
    category: "finance",
    headline: "KKR Closes $20bn Infrastructure Fund, Largest in Private Markets History",
    brief: "KKR's Global Infrastructure Investors IV surpassed its $15bn target after 14 months of fundraising, reflecting surging institutional appetite for real assets amid rate uncertainty.",
    tags: ["Private Equity", "Asset Management", "Global", "M&A"],
    sources: ["Bloomberg", "Preqin", "FT"],
    time: "4 Feb",
    date: "2025-02-04",
    market: "NYSE",
    verified: true,
  },
  {
    id: "a6",
    category: "breaking",
    headline: "US Treasury Imposes New Sanctions on Iranian Petrochemical Network",
    brief: "OFAC designated 16 entities and 4 individuals linked to a sanctions-evasion scheme moving over $1.5bn in oil proceeds through shell companies in the UAE and China.",
    tags: ["United States", "Regulation", "Compliance", "Global"],
    sources: ["US Treasury", "Reuters", "WSJ"],
    time: "5 Feb",
    date: "2025-02-05",
    market: null,
    verified: true,
  },
  {
    id: "a7",
    category: "markets",
    headline: "Nikkei 225 Surges Past 40,000 for First Time Since 1990 Bubble Peak",
    brief: "Japanese equities were lifted by a weaker yen, strong corporate earnings from exporters, and continued foreign inflows drawn by the Bank of Japan's cautious policy stance.",
    tags: ["Nikkei", "Asia-Pacific", "Markets"],
    sources: ["Bloomberg", "Nikkei Asia", "Reuters"],
    time: "7 Feb",
    date: "2025-02-07",
    market: "Nikkei",
    verified: true,
  },
  {
    id: "a8",
    category: "legal",
    headline: "EU Court Rules Microsoft Teams Bundle Violated Competition Law",
    brief: "The General Court upheld a €250m Commission fine, finding that bundling Teams with Microsoft 365 foreclosed rivals in a nascent market, setting a precedent for Big Tech bundling cases.",
    tags: ["Antitrust", "European Union", "Regulation", "Litigation"],
    sources: ["EU Court of Justice", "FT", "Reuters"],
    time: "8 Feb",
    date: "2025-02-08",
    market: null,
    verified: true,
  },

  // ── Week of 27 Jan – 2 Feb ─────────────────────────────────────────────────
  {
    id: "a9",
    category: "finance",
    headline: "HSBC Announces $3bn Buyback After Asia Profits Surge 22%",
    brief: "Strong performance in wealth management and transaction banking across Hong Kong and Singapore drove group pre-tax profits above £22bn for the full year, ahead of consensus.",
    tags: ["HSBC", "Banking", "Asia-Pacific", "LSE"],
    sources: ["FT", "Bloomberg", "Reuters"],
    time: "28 Jan",
    date: "2025-01-28",
    market: "LSE",
    verified: true,
  },
  {
    id: "a10",
    category: "legal",
    headline: "DOJ Approves Tapestry–Capri Merger After Fashion Group Concessions",
    brief: "Antitrust regulators cleared the $8.5bn luxury fashion deal after the parties agreed to divest the Versace brand, resolving concerns about reduced competition in accessible luxury.",
    tags: ["M&A", "Antitrust", "United States", "M&A Law"],
    sources: ["DOJ", "WSJ", "Bloomberg"],
    time: "29 Jan",
    date: "2025-01-29",
    market: "NYSE",
    verified: true,
  },
  {
    id: "a11",
    category: "markets",
    headline: "Bank of Canada Cuts to 3.25% as Housing Market Cools Further",
    brief: "The BoC's second cut in three months comes as home prices fall 8% year-on-year and the unemployment rate creeps toward 7%, raising recession risk in the near term.",
    tags: ["Monetary Policy", "Asia-Pacific", "Banking"],
    sources: ["Bank of Canada", "Reuters", "Globe and Mail"],
    time: "30 Jan",
    date: "2025-01-30",
    market: "TSX",
    verified: true,
  },
  {
    id: "a12",
    category: "breaking",
    headline: "Citadel Fined $7m by SEC Over Dark Pool Transparency Failures",
    brief: "The SEC found that Citadel Securities failed to report over 3,200 dark pool trades to FINRA's trade reporting facility within the required 10-second window over an 18-month period.",
    tags: ["SEC", "Compliance", "United States", "Regulation"],
    sources: ["SEC", "Bloomberg", "Reuters"],
    time: "31 Jan",
    date: "2025-01-31",
    market: "NYSE",
    verified: true,
  },
];
